import { test } from "node:test";
import assert from "node:assert/strict";
import argon2 from "argon2";
import { login, register, registerSchema, requestPasswordReset, resetPassword, verifyEmail } from "./auth";
import { db } from "./db";
import { normalizedEmail, randomToken, hashToken, rateLimit } from "./security";

test("registro pendiente no se reemplaza ni activa antes de verificar", { skip: !process.env.DATABASE_URL && "DATABASE_URL no configurada" }, async () => {
  const sql = db();
  const email = normalizedEmail(`fase1-${randomToken().slice(0, 12)}@example.test`);
  const expiredEmail = normalizedEmail(`fase1-${randomToken().slice(0, 12)}@example.test`);
  const originalFetch = globalThis.fetch;
  const originalEmailKey = process.env.RESEND_API_KEY;
  const originalEmailFrom = process.env.EMAIL_FROM;
  const sent: string[] = [];
  process.env.RESEND_API_KEY = "test-key";
  process.env.EMAIL_FROM = "test@example.test";
  globalThis.fetch = async (_url, init) => {
    const body = JSON.parse(String(init?.body)) as { to: string; text: string };
    sent.push(body.text);
    assert.equal(body.to, email);
    return new Response(JSON.stringify({ id: "test-delivery" }), { status: 200 });
  };
  try {
    const input = { email, password: "contraseña-segura-fase1", firstName: "Usuario", lastName: "Test", phone: "12345678" };
    assert.equal(registerSchema.safeParse({ ...input, email: "no-email" }).success, false);
    assert.equal(registerSchema.safeParse({ ...input, password: "123" }).success, false);
    assert.equal(await login("no-existe@example.test", input.password), null);
    assert.equal(await register(input, "http://localhost:3000"), true);
    const first = await sql`SELECT token_hash, password_hash FROM pending_users WHERE email = ${email}`;
    assert.equal(first.length, 1);
    assert.equal((await sql`SELECT count(*)::int AS total FROM users WHERE email = ${email}`)[0].total, 0);
    assert.equal(await register({ ...input, password: "otra-contraseña-muy-segura" }, "http://localhost:3000"), false);
    const second = await sql`SELECT token_hash, password_hash FROM pending_users WHERE email = ${email}`;
    assert.equal(second[0].token_hash, first[0].token_hash);
    assert.equal(second[0].password_hash, first[0].password_hash);
    assert.equal(sent.length, 1);
    assert.equal(await login(email, input.password), null, "un pendiente no puede iniciar sesión");
    const oldToken = randomToken();
    await sql`INSERT INTO pending_users (email, password_hash, first_name, last_name, phone, token_hash, expires_at) VALUES (${expiredEmail}, ${first[0].password_hash}, 'Test', 'Expirado', '12345678', ${hashToken(oldToken)}, now() - interval '1 minute')`;
    assert.equal(await verifyEmail(oldToken), false);
    const token = sent[0].match(/token=([a-f0-9]{64})/)?.[1];
    assert.ok(token);
    assert.equal(hashToken(token), first[0].token_hash);
    assert.equal(await verifyEmail(token), true);
    assert.equal(await verifyEmail(token), false);
    const users = await sql`SELECT id, role, email_verified_at, password_hash FROM users WHERE email = ${email}`;
    assert.equal(users.length, 1);
    assert.equal(users[0].role, "CUSTOMER");
    assert.ok(users[0].email_verified_at);
    assert.notEqual(users[0].password_hash, input.password);
    assert.equal(await argon2.verify(users[0].password_hash, input.password), true);
    assert.equal(await login(email, "clave-incorrecta"), null);
    assert.equal((await sql`SELECT count(*)::int AS total FROM pending_users WHERE email = ${email}`)[0].total, 0);
    assert.equal(await register(input, "http://localhost:3000"), false);
    await requestPasswordReset("no-existe@example.test", "http://localhost:3000");
    assert.equal(sent.length, 1, "no se revela ni envía recovery a cuentas inexistentes");
    await requestPasswordReset(email, "http://localhost:3000");
    const resetToken = sent[1].match(/token=([a-f0-9]{64})/)?.[1];
    assert.ok(resetToken);
    assert.equal((await sql`SELECT token_hash FROM password_resets WHERE user_id = ${users[0].id}`)[0].token_hash, hashToken(resetToken));
    const oldSession = randomToken();
    await sql`INSERT INTO sessions (token_hash, user_id, expires_at) VALUES (${hashToken(oldSession)}, ${users[0].id}, now() + interval '1 day')`;
    assert.equal(await resetPassword(resetToken, "contraseña-nueva-segura"), true);
    assert.equal(await resetPassword(resetToken, "contraseña-nueva-segura"), false);
    assert.equal((await sql`SELECT count(*)::int AS total FROM sessions WHERE user_id = ${users[0].id}`)[0].total, 0);
    const updated = await sql`SELECT password_hash FROM users WHERE id = ${users[0].id}`;
    assert.equal(await argon2.verify(updated[0].password_hash, "contraseña-nueva-segura"), true);
    await sql`UPDATE users SET disabled_at = now() WHERE id = ${users[0].id}`;
    assert.equal(await login(email, "contraseña-nueva-segura"), null, "una cuenta deshabilitada no puede entrar");
    const rateKey = `fase1:${randomToken()}`;
    assert.equal(await rateLimit(rateKey, 2, 15), true);
    assert.equal(await rateLimit(rateKey, 2, 15), true);
    assert.equal(await rateLimit(rateKey, 2, 15), false);
  } finally {
    globalThis.fetch = originalFetch;
    if (originalEmailKey === undefined) delete process.env.RESEND_API_KEY;
    else process.env.RESEND_API_KEY = originalEmailKey;
    if (originalEmailFrom === undefined) delete process.env.EMAIL_FROM;
    else process.env.EMAIL_FROM = originalEmailFrom;
    await sql`DELETE FROM pending_users WHERE email IN (${email}, ${expiredEmail})`;
    await sql`DELETE FROM users WHERE email = ${email}`;
  }
});